apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: review-apps
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: review-apps
  source:
    repoURL: https://github.com/nicklinnell/review-apps.git
    targetRevision: HEAD
    path: helm
  destination:
    server: https://kubernetes.default.svc
    namespace: review-apps
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
