apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{.APP_ID}}"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: previews
  source:
    path: helm
    repoURL: https://github.com/nicklinnell/review-apps.git
    targetRevision: HEAD
    helm:
      values: |
        image:
          repository: "nicklinnell/hellokyan:{{.APP_ID}}"
          tag: master
      version: v3
  destination:
    namespace: "{{.APP_ID}}"
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
